// Writes the strength, core and finisher half of the movement library into
// training/index.html as plain HTML, so it is in the page source rather than
// only inside movements.js where no crawler and no reader without JavaScript
// will ever see it. The mobility half is written by hand on that page already.
//
//   node tools/build-library.js          rewrite the block
//   node tools/build-library.js --check  exit 1 if the block is out of date
//
// Run from the repo root. Nothing on the site loads this file.

const fs = require('fs');
const vm = require('vm');

const START = '<!-- library:start -->';
const END = '<!-- library:end -->';
const PAGE = 'training/index.html';

// movements.js is a plain script meant for a browser. Give it just enough of one.
const sandbox = {localStorage: {getItem: () => null, setItem: () => {}}, document: undefined};
vm.createContext(sandbox);
// top-level const stays in the script's own scope, so hand the three out explicitly
vm.runInContext(fs.readFileSync('movements.js', 'utf8') +
  '\n;globalThis.__lib = {LIB, GROUPS, START_KG};', sandbox);
const {LIB, GROUPS, START_KG} = sandbox.__lib;

const KIT = ['bodyweight', 'a band', 'dumbbells', 'a full gym'];
const AVOID = {
  deepknee: 'deep knee flexion', overhead: 'overhead loading',
  jump: 'jumping and impact', floor: 'floor work', grip: 'heavy grip',
};
const esc = s => String(s).replace(/&(?![a-z]+;|#\d+;)/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
// The page is written with HTML entities, not literal punctuation. Match it.
const ent = s => esc(s).replace(/—/g, '&mdash;').replace(/–/g, '&ndash;')
  .replace(/’/g, '&rsquo;').replace(/×/g, '&times;').replace(/·/g, '&middot;');

const line = x => {
  const bits = [KIT[x.e]];
  const kg = START_KG[x.n];
  if (x.d) bits.push(x.d);
  else if (typeof kg === 'number') bits.push('starts at ' + kg + ' kg');
  let s = `<strong>${ent(x.n)}</strong> &mdash; ${bits.join(', ')}`;
  const held = (x.a || []).map(t => AVOID[t]).filter(Boolean);
  if (held.length) s += `. Held back when you ask it to avoid ${ent(held.join(' or '))}`;
  return `    <li>${s}.</li>`;
};

const WANT = ['hinge', 'squat', 'push', 'pull', 'acc', 'core', 'fin'];
const seen = new Set();
const blocks = WANT.map(key => {
  const label = (GROUPS.find(g => g[0] === key) || [null, key])[1];
  const items = LIB.filter(x => x.p === key && !seen.has(x.n) && seen.add(x.n) !== undefined);
  if (!items.length) return '';
  return `  <h3>${ent(label)}</h3>\n  <ul>\n${items.map(line).join('\n')}\n  </ul>`;
}).filter(Boolean);

const body = [
  START,
  '  <!-- Generated by tools/build-library.js from movements.js. Edit the movement',
  '       there and re-run it; do not edit these lists by hand. -->',
  ...blocks,
  '  ' + END,
].join('\n');

const page = fs.readFileSync(PAGE, 'utf8');
const from = page.indexOf(START), to = page.indexOf(END);
if (from < 0 || to < 0) {
  console.error(`${PAGE} has no ${START} … ${END} block to fill.`);
  process.exit(2);
}
const next = page.slice(0, from) + body + page.slice(to + END.length);

if (process.argv.includes('--check')) {
  if (next === page) { console.log(`${PAGE}: the movement library matches movements.js.`); process.exit(0); }
  console.error(`${PAGE}: the movement library is out of date. Run: node tools/build-library.js`);
  process.exit(1);
}
fs.writeFileSync(PAGE, next);
const n = LIB.filter(x => WANT.includes(x.p)).length;
console.log(`${PAGE}: wrote ${n} movements across ${blocks.length} groups.`);
